import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Futebolada",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Navigation Bar */}
        <nav className="bg-black text-blue-400 p-4 flex justify-between font-bold">
          <h1 className="text-xl font-bold">Futebolada</h1>
          <div className="space-x-6">
            <Link href="/" className="hover:underline ">Home</Link>
            <Link href="/add-player" className="hover:underline">Add Player</Link>
            <Link href="/players-stats" className="hover:underline">Players Stats</Link>
            <Link href="/players-list" className="hover:underline">Players List</Link>
          </div>
        </nav>
        
        {/* Page Content */}
        <main className="p-6">{children}</main>
      </body>
    </html>
  );
}
